-- Uong Bi GO - Neon / PostgreSQL schema
-- Run this file once in Neon SQL Editor after creating a fresh database.

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ho_ten VARCHAR(150) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  mat_khau TEXT NOT NULL,
  vai_tro VARCHAR(20) NOT NULL DEFAULT 'ROLE_BUYER'
    CHECK (vai_tro IN ('ROLE_BUYER', 'ROLE_STAFF', 'ROLE_ADMIN')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS menu_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ten_mon VARCHAR(200) NOT NULL,
  don_gia NUMERIC(12, 2) NOT NULL CHECK (don_gia > 0),
  mo_ta TEXT NOT NULL DEFAULT '',
  hinh_anh TEXT NOT NULL DEFAULT '',
  trang_thai VARCHAR(20) NOT NULL DEFAULT 'CON_HANG'
    CHECK (trang_thai IN ('CON_HANG', 'HET_HANG', 'DA_XOA')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ma_nguoi_dung BIGINT NOT NULL REFERENCES users(id),
  ma_don_rut_gon VARCHAR(30) NOT NULL UNIQUE,
  ngay_dat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  thoi_gian_nhan TIMESTAMPTZ,
  trang_thai VARCHAR(40) NOT NULL,
  tong_tien NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (tong_tien >= 0),
  ma_qr VARCHAR(100),
  thoi_han_thanh_toan TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ma_don_hang BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  ma_mon BIGINT NOT NULL REFERENCES menu_items(id),
  ten_mon VARCHAR(200) NOT NULL,
  so_luong INTEGER NOT NULL CHECK (so_luong > 0),
  don_gia NUMERIC(12, 2) NOT NULL CHECK (don_gia >= 0)
);

CREATE INDEX IF NOT EXISTS orders_user_date_idx ON orders (ma_nguoi_dung, ngay_dat DESC);
CREATE INDEX IF NOT EXISTS orders_status_date_idx ON orders (trang_thai, ngay_dat ASC);

-- Demo accounts retain the old SHA-256 hashes only for the first login.
-- The API automatically upgrades a verified legacy hash to salted scrypt.
INSERT INTO users (id, ho_ten, email, mat_khau, vai_tro) VALUES
  (1, 'Quan ly Canteen', 'admin@uongbigo.vn', 'e86f78a8a3caf0b60d8e74e5942aa6d86dc150cd3c03338aef25b7d2d7e3acc7', 'ROLE_ADMIN'),
  (2, 'Nhan vien bep', 'bep@uongbigo.vn', '671989e46cd483c5235eeb3e278f13139bcbc7d3d23dcac19a583190d4b04ee5', 'ROLE_STAFF'),
  (3, 'Sinh vien Demo', 'sv@uongbigo.vn', '471425fac023b25a0f81aaac21cc5cfc6ccb9203c732105f818ae2c84836ddf3', 'ROLE_BUYER')
ON CONFLICT (id) DO NOTHING;

INSERT INTO menu_items (id, ten_mon, don_gia, mo_ta, trang_thai) VALUES
  (1, 'Com tam suon bi', 32000, 'Com tam suon nuong, bi, cha, trung op la', 'CON_HANG'),
  (2, 'Bun cha Ha Noi', 30000, 'Bun, cha nuong than hoa, nuoc mam chua ngot', 'CON_HANG'),
  (3, 'Pho bo tai', 35000, 'Pho bo truyen thong, nuoc dung ninh xuong', 'CON_HANG'),
  (4, 'Bun dau mam tom', 28000, 'Bun, dau ran, cha com, mam tom nguyen chat', 'HET_HANG'),
  (5, 'Mi xao hai san', 33000, 'Mi xao gion cung tom, muc, rau cu', 'CON_HANG'),
  (6, 'Salad uc ga', 29000, 'Uc ga ap chao, rau xa lach, sot me rang', 'CON_HANG')
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE((SELECT MAX(id) FROM users), 1));
SELECT setval(pg_get_serial_sequence('menu_items', 'id'), COALESCE((SELECT MAX(id) FROM menu_items), 1));
